export type WebosUri = { uri: string; type: string };

type WebosUriList = {
  [key: string]: WebosUri;
};

export const webosUriList: WebosUriList = {
  get_services: { uri: 'api/getServiceList', type: 'ssap' },
  set_mute: { uri: 'audio/setMute', type: 'ssap' },
  get_audio_status: { uri: 'audio/getStatus', type: 'ssap' },
  get_volume: { uri: 'audio/getVolume', type: 'ssap' },
  set_volume: { uri: 'audio/setVolume', type: 'ssap' },
  volume_up: { uri: 'audio/volumeUp', type: 'ssap' },
  volume_down: { uri: 'audio/volumeDown', type: 'ssap' },
  get_current_app_info: { uri: 'com.webos.applicationManager/getForegroundAppInfo', type: 'ssap' },
  launch_app: { uri: 'com.webos.applicationManager/launch', type: 'ssap' },
  get_apps: { uri: 'com.webos.applicationManager/listLaunchPoints', type: 'ssap' },
  get_app_status: { uri: 'com.webos.service.appstatus/getAppStatus', type: 'ssap' },
  send_enter: { uri: 'com.webos.service.ime/sendEnterKey', type: 'ssap' },
  send_delete: { uri: 'com.webos.service.ime/deleteCharacters', type: 'ssap' },
  insert_text: { uri: 'com.webos.service.ime/insertText', type: 'ssap' },
  set_3d_on: { uri: 'com.webos.service.tv.display/set3DOn', type: 'ssap' },
  set_3d_off: { uri: 'com.webos.service.tv.display/set3DOff', type: 'ssap' },
  get_software_info: { uri: 'com.webos.service.update/getCurrentSWInformation', type: 'ssap' },
  media_play: { uri: 'media.controls/play', type: 'ssap' },
  media_stop: { uri: 'media.controls/stop', type: 'ssap' },
  media_pause: { uri: 'media.controls/pause', type: 'ssap' },
  media_rewind: { uri: 'media.controls/rewind', type: 'ssap' },
  media_fast_forward: { uri: 'media.controls/fastForward', type: 'ssap' },
  media_close: { uri: 'media.viewer/close', type: 'ssap' },
  power_off: { uri: 'system/turnOff', type: 'ssap' },
  power_on: { uri: 'system/turnOn', type: 'ssap' },
  show_message: { uri: 'system.notifications/createToast', type: 'ssap' },
  close_toast: { uri: 'system.notifications/closeToast', type: 'ssap' },
  create_alert: { uri: 'system.notifications/createAlert', type: 'ssap' },
  close_alert: { uri: 'system.notifications/closeAlert', type: 'ssap' },
  launcher_close: { uri: 'system.launcher/close', type: 'ssap' },
  get_app_state: { uri: 'system.launcher/getAppState', type: 'ssap' },
  get_system_info: { uri: 'system/getSystemInfo', type: 'ssap' },
  launch: { uri: 'system.launcher/launch', type: 'ssap' },
  open: { uri: 'system.launcher/open', type: 'ssap' },
  get_system_settings: { uri: 'settings/getSystemSettings', type: 'ssap' },
  tv_channel_down: { uri: 'tv/channelDown', type: 'ssap' },
  tv_channel_up: { uri: 'tv/channelUp', type: 'ssap' },
  get_tv_channels: { uri: 'tv/getChannelList', type: 'ssap' },
  get_channel_info: { uri: 'tv/getChannelProgramInfo', type: 'ssap' },
  get_current_channel: { uri: 'tv/getCurrentChannel', type: 'ssap' },
  get_inputs: { uri: 'tv/getExternalInputList', type: 'ssap' },
  set_channel: { uri: 'tv/openChannel', type: 'ssap' },
  set_input: { uri: 'tv/switchInput', type: 'ssap' },
  close_web_app: { uri: 'webapp/closeWebApp', type: 'ssap' },
  input_socket: { uri: 'com.webos.service.networkinput/getPointerInputSocket', type: 'ssap' },
  calibration: { uri: 'externalpq/setExternalPqData', type: 'ssap' },
  get_calibration: { uri: 'externalpq/getExternalPqData', type: 'ssap' },
  get_sound_output: { uri: 'com.webos.service.apiadapter/audio/getSoundOutput', type: 'ssap' },
  change_sound_output: { uri: 'com.webos.service.apiadapter/audio/changeSoundOutput', type: 'ssap' },
  get_power_state: { uri: 'com.webos.service.tvpower/power/getPowerState', type: 'ssap' },
  turn_off_screen: { uri: 'com.webos.service.tvpower/power/turnOffScreen', type: 'ssap' },
  turn_on_screen: { uri: 'com.webos.service.tvpower/power/turnOnScreen', type: 'ssap' },
  set_system_settings: { uri: 'com.webos.settingsservice/setSystemSettings', type: 'luna' },
};
